Pandas is powerful python library widely used for data manipulation and analysis. It has data structures and functions that simplify working with structured data(tables). It uses NumPy internally. Below are some of the things we can do with Pandas.
* Efficient data handling : Excel cannot handle millons of records in tables, it becomes very slow, Pandas can do it efficiently.
* Data alignment
* Handling missing data
* Data integration
* Flexible data transformation
* Integration with other libraries  

Pandas library runs on a single thread, but still very efficient.  
Pandas is sometimes used as a tool in agents to do mathematical computations, to enhance performance. LLM's are bad at doing mathematical computations.

# Data structures
* Series : One dimentional array with axis labels, like a column in excel.
* DataFrame : Two dimentional data structure with labeled rows and columns, like a sheet in excel(table).

Pandas can also be used to read non-relational databases, by loading the file items into a single column.

In [2]:
try:
    import numpy as np
except ImportError:
    print("NumPy not found, installing")
    %pip install numpy

print(np.__version__)

try:
    import pandas as pd
except ImportError:
    print("Pandas not found, installing")
    %pip install pandas

print(pd.__version__)

2.4.6
3.0.3

In [3]:
# Create a dataframe by reading data from a csv file
csv_url = "data/train.csv"
df = pd.read_csv(csv_url) # Pandas has many functions to read from different file types(data sources) 
                          # like read_json to read from json files
                          # It can also read from databases, like read_sql
df.head(5) # Read the first 5 rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.info() # Get some basic information about the dataset
df.describe() # Get statistics for all the numeric columns

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [6]:
# Select a single column, returns a sereis
df["Age"]
# Select a group of columns, returns a dataframe
df[["Age", "Fare"]]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [7]:
# Filtering, similar to NumPy
df["Fare"] > 15 # Returns a True/False column with which we can filter
df[df["Fare"] > 15] # Records who paid more than 15 pounds
df[df["Fare"] > 15]["Fare"] # Get the Fare column for the records who paid more than 15 pounds
df[df["Fare"] > 15]["Fare"].mean() # Get the average fare of people paying more than 15 pounds

np.float64(56.90295357967668)

In [8]:
# Sorting
df.sort_values("Age", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [9]:
# For an empty cell value, pandas fills it up with NaN(Not a number)
# Replacing an empty value
df.dropna() # Drop all records with null in any of the columns and return the new df
df["Age"].isna() # Returns true for all the rows which have NaN for Age column, else false
df["Age"].isna().sum() # Count the number of rows with NaN values
df["Age"] = df["Age"].fillna(df["Age"].mean()) # Fillup the NaN's of the age column with the average value

In [10]:
# Data analysis : groupby, aggregate
# Does sex, age or pclass has anything to do with thier survival rate
df.groupby("Pclass").agg({"Survived" : "mean"})
df.groupby("Sex").agg({"Survived" : "mean"})
df.groupby(["Pclass", "Sex"]).agg({"Survived" : "mean"})
df.groupby("Survived").agg({"Fare" : "mean", "Age" : ["mean", "median"]}) # Fare and age based on survival

               Fare        Age
               mean       mean     median
Survived
0         22.117887  30.415100  29.699118
1         48.395408  28.549778  29.699118

In [11]:
# Get the value based on index, iloc and loc
df.iloc[0,0] # Get the value based on row index and column index
df.loc[0, "Survived"] # Get the value based on row index and column name

# Drops rows and columns, axis = 0 stands for rows and axis = 1 stands for columns
df.drop("PassengerId", axis=1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,NaN,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S
889,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,NaN,Q

In [25]:
# Apply, to apply a custom function to a column
# Add a new column in titanic which tells if the person is eligible to vote
df["eligible_to_vote"] = df["Age"].apply(lambda x: x > 18)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,eligible_to_vote
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,True